[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    unit: unit test
    integration: test integration
    supabase: test khusus supabase
    limit_api: test pada API terbatas
    core: test pada proses inti

filterwarnings =
    ignore::DeprecationWarning

; addopts = -v --tb=short
; log_cli = true
; log_cli_level = INFO